{{- if .Values.global.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
{{ include "wave-labels.chart" . | indent 4 }}
  name: {{ template "wave-fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - list
      - get
      - update
      - patch
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - update
      - patch
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/finalizers
      - daemonsets
      - daemonsets/finalizers
      - statefulsets
      - statefulsets/finalizers
    verbs:
      - list
      - get
      - update
      - patch
      - watch
{{- end }}
